# Generated by Django 4.2.7 on 2023-11-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningmodule',
            name='link',
        ),
        migrations.AddField(
            model_name='listeningmodule',
            name='audio_file',
            field=models.FileField(default='default_audio.mp3', upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='listeningmodule',
            name='captions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listeningmodule',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='ModuleQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.listeningmodule')),
            ],
        ),
    ]
