# Generated by Django 4.2.7 on 2023-11-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0003_alter_listeningmodule_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleqa',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleqa',
            name='question_type',
            field=models.CharField(choices=[('fill_in_the_gaps', 'Fill in the Gaps'), ('multiple_choice', 'Multiple Choice')], default='fill_in_the_gaps', max_length=20),
        ),
    ]
